default['lc4_jenkins']['version'] = 'jenkins-2.89.4'
default['lc4_jenkins']['password'] = 'none'
default['lc4_jenkins']['homedir'] = '/var/lib/jenkins'
default['lc4_jenkins']['groupid'] = '994'
default['lc4_jenkins']['userguid'] = '996'
default['lc4_jenkins']['shell'] = '/bin/bash'
default['lc4_jenkins']['svcacct'] = 'jenkins'
